# Generated by Django 3.0.6 on 2020-05-23 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_text', models.CharField(blank=True, help_text='Search Text', max_length=255, null=True)),
                ('relevance_number', models.IntegerField(help_text='Relevence Number')),
            ],
        ),
    ]
